#!/usr/bin/env bash
# Looping through the echo command and waiting for 2 seconds indefinitely
trap "{ echo 'I am invincible!!!'; }" SIGTERM
while true; do echo "To infinity and beyond"; sleep 2; done
