#!/usr/bin/env bash
# Creates the file /tmp/myscript.pid containing its PID, Displays To infinity and beyond indefinitely, Displays I hate the kill command when receiving a SIGTERM signal, Displays Y U no love me?! when receiving a SIGINT signal, Deletes the file /tmp/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo "$$" > /tmp/myscript.pid
trap "{ rm /tmp/myscript.pid; echo 'I hate the kill command'; exit; }" SIGTERM
trap "{ rm /tmp/myscript.pid; exit; }" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true; do sleep 2 && echo "To infinity and beyond"; done
