#!/usr/bin/env bash
# Creates the file /tmp/myscript.pid containing its PID, Displays To infinity and beyond indefinitely, Displays I hate the kill command when receiving a SIGTERM signal, Displays Y U no love me?! when receiving a SIGINT signal, Deletes the file /tmp/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
trap "echo 'Y U no love me?!'" SIGINT
trap "{ rm /tmp/myscript.pid; echo'I ahte the kill command'; exit; }" SIGTERM
trap "{ rm /tmp/myscript.pid; exit; }" SIGQUIT
pgrep bash > /tmp/myscript.pid
while true; do echo "To infinity and beyond"; sleep 2; done
